const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Ledger,settlement}=require('../dist/core/ledger.js');
const Replay=require('../dist/core/replay.js');
const {PatternBook,detect}=require('../dist/core/patterns.js');
function ledger(){const l=new Ledger();l.mark(100,0,60);return l;}
function signal(l,id='s1'){l.registerSignal({id,name:'双重底',side:'long',status:'confirmed'});}
test('plain clicking never adds bonus or streak',()=>{const l=ledger();for(let i=0;i<20;i++){l.order('long',10);l.order('short',10);}assert.equal(l.bonus,0);assert.equal(l.streak,0);assert.equal(l.cycles.length,0);});
test('partial closes count as one complete profitable cycle, including all fees',()=>{const l=ledger();l.order('long',10);l.mark(110,1,60);for(let i=0;i<5;i++)l.order('short',10);assert.equal(l.streak,0);assert.equal(l.cycles.length,0);l.close();assert.equal(l.streak,1);assert.equal(l.cycles.length,1);assert.equal(l.cycles[0].netPnl,l.realized);assert.ok(l.cycles[0].fees>1.5);});
test('same-price cycle loses fees and resets streak',()=>{const l=ledger();l.order('long',10);l.mark(110,1,60);l.close();l.order('long',10);l.close();assert.equal(l.streak,0);assert.ok(l.cycles[1].netPnl<0);});
test('confirmed timely execution earns only after full cycle profit',()=>{const l=ledger();signal(l);l.order('long',10);assert.equal(l.bonus,0);l.mark(110,1,60);l.order('short',10);assert.equal(l.bonus,0);l.close();assert.ok(l.bonus>0);assert.equal(l.rewardCount,1);assert.ok(l.bonus<=l.cycles[0].netPnl*2);});
test('late execution and candidate-only signals receive no reward',()=>{for(const late of [false,true]){const l=ledger();l.registerSignal({id:'s',name:'x',side:'long',status:late?'confirmed':'candidate'});l.mark(100,20,64);l.order('long',10);l.mark(110,21,64);l.close();assert.equal(l.bonus,0);}});
test('invalidated signal cannot pay even when cycle profits',()=>{const l=ledger();signal(l);l.order('long',10);l.invalidateSignal('s1');l.mark(110,1,60);l.close();assert.equal(l.bonus,0);});
test('one signal cannot be claimed by repeated cycles',()=>{const l=ledger();signal(l);l.order('long',10);l.mark(110,1,60);l.close();const bonus=l.bonus;l.order('long',10);l.mark(120,2,60);l.close();assert.equal(l.bonus,bonus);});
test('profit on unrelated lots cannot pay a losing signal lot',()=>{const l=ledger();l.order('long',50);l.mark(120,1,60);signal(l);l.order('long',10);l.mark(115,2,60);l.close();assert.ok(l.cycles[0].netPnl>0);assert.equal(l.bonus,0);});
test('MAX reserves fees and rejects unavailable margin',()=>{const l=ledger();l.order('short',100);assert.ok(l.wallet>=l.position.margin);assert.ok(l.available()<.02);const n=l.fills.length;assert.equal(l.order('short',10).ok,false);assert.equal(l.fills.length,n);});
test('weighted average and opposite netting preserve single side',()=>{const l=ledger();l.order('long',10);l.mark(110,1,60);l.order('long',10);assert.ok(l.position.avgPrice>100&&l.position.avgPrice<110);const n=l.position.qty;l.order('short',50);assert.equal(l.position.side,'long');assert.ok(Math.abs(l.position.qty-n*.5)<1e-8);});
test('settlement is proportional and loss capped at entry',()=>{assert.deepEqual(settlement(200,11000,10000),{payout:220,netPoints:20,returnRate:11000/10000-1});assert.equal(settlement(200,9000,10000).netPoints,-20);assert.equal(settlement(200,0,10000).netPoints,-200);assert.equal(settlement(200,100000,10000).netPoints,1800);assert.equal(settlement(0,11000,10000).payout,0);});
test('finish is idempotent and closes any remaining position once',()=>{const l=ledger();l.order('short',10);l.mark(90,1,60);l.finish();const n=l.fills.length,w=l.wallet;l.finish();assert.equal(l.fills.length,n);assert.equal(l.wallet,w);assert.equal(l.cycles.length,1);assert.equal(l.order('long',10).ok,false);});
function micro(n=3000){return Array.from({length:n},(_,i)=>({time:i*60000,open:100+i*.01,high:102+i*.01,low:98+i*.01,close:101+i*.01,volume:1}));}
test('500 candles plus warmup use real lower bars with seeded selection',()=>{const groups=Replay.groupBars(micro(),60000,5);assert.equal(groups.length,600);const a=Replay.selectSegment(groups,42);const b=Replay.selectSegment(groups,42);assert.equal(a.length,560);assert.equal(a[0].time,b[0].time);assert.equal(a[0].steps.length,5);});
test('unrevealed future high/low/close cannot alter current candle',()=>{const groups=Replay.groupBars(micro(10),60000,5),g=groups[0];const a=Replay.begin(g,1);g.close=1;g.high=99999;g.low=.01;const b=Replay.begin(g,1);assert.deepEqual(a,b);Replay.reveal(a,g.steps[0]);assert.equal(a.close,g.steps[0].close);assert.equal(a.high,g.steps[0].high);assert.notEqual(a.close,g.close);});
test('incomplete lower-bar group is excluded and insufficient matches fail',()=>{const bars=micro(20);bars.splice(2,1);const groups=Replay.groupBars(bars,60000,5);assert.equal(groups.length,3);assert.throws(()=>Replay.selectSegment(groups,1));});
test('candidate confirms only later, then invalidates on failed breakout',()=>{const book=new PatternBook();const note=book.add({name:'测试底',side:'long',category:'反转',endId:1,lines:[[{id:0,price:90},{id:1,price:92}],[{id:0,price:100},{id:1,price:100}]]},0);assert.equal(note.status,'candidate');book.advance([{id:1,close:110}],1);assert.equal(note.status,'candidate');book.advance([{id:2,close:101}],2);assert.equal(note.status,'confirmed');book.advance([{id:3,close:99}],3);assert.equal(note.status,'invalid');});
test('pattern detector accepts short history without future access',()=>{assert.deepEqual(detect([]),[]);assert.deepEqual(detect(micro(12).map((b,id)=>({...b,id}))),[]);});
test('same command log and observations produce identical results',()=>{function run(){const l=ledger();signal(l);l.order('long',25);l.mark(105,1,60);l.order('long',10);l.order('short',25);l.mark(110,2,60);l.close();return {snapshot:l.snapshot(),fills:l.fills,cycles:l.cycles};}assert.deepEqual(run(),run());});
